### ISSUE TITLE
Create RBIS Master List of Taxa

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#11]

**Comment by mmindje** [comment]
A master list of each Taxa is needed.

Our priority shall be birds @Thacien

**Comment by Thacien1** [comment]
> A master list of each Taxa is needed.
> 
> Our priority shall be birds @Thacien

Sure! Thanks

**Comment by mmindje** [comment]
#Birds D1, D3 already done.

After Hellen has given comments we shall go-ahead with other taxa as you are doing it with Daniel @Thacien1

**Comment by mmindje** [comment]
I think now @DanielIgirimbabazi Can join the team

**Comment by helendallas** [comment]
Please see #5 for Bird Master List, and #13 for Bird data
