### ISSUE TITLE
Populate Bird data template

### ISSUE THREAD

**Issue by helendallas** [mmindje/Data-management-FRC-RBIS#13]
@mmindje We need to have a meeting to modify the Data Upload Template for birds, so that the RBIS team can begin capturing bird data

**Comment by helendallas** [comment]
@mmindje 

Here is the RBIS Bird Data 26June2020.xlsx from today's session.  As mentioned, the RBIS data team can now customise the RBIS Bird Data upload template according to the bird data that you have.  Specifically, you can delete any columns that are not required.

Then add all bird occurrence records to the RBIS Bird Data file.

[RBIS Bird Data 26June2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4844772/RBIS.Bird.Data.26June2020.xlsx)

**Comment by mmindje** [comment]
Thank you @helendallas , the team is already working on the bird data template.

**Comment by helendallas** [comment]
@mmindje Perhaps send me back the RBIS Bird data upload template once you have customised it, for a quick check. I Ideally with some of the bird data captured so that I can check on formats etc before you go to far.

**Comment by mmindje** [comment]
Sure, @Thacien1 can you send the template to Hellen
Thank you

**Comment by Thacien1** [comment]
Dear @helendallas ,
Here is a bird data upload template. Thank you
[RBIS.Bird.Data. 2 July 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4864226/RBIS.Bird.Data.2.July.2020.xlsx)

**Comment by helendallas** [comment]
@Thacien1  @mmindje 

Thanks for the data file. Remember it is not necessary to add GBIF data to this file. That will be harvested directly from GBIF and served as optional data to add. 

You should ony focus on the other bird datasets that you have for Rwanda.

![image](https://user-images.githubusercontent.com/45286876/86438366-ae4da900-bd06-11ea-8618-a8eeeb643bcb.png)

**Comment by DanielIgirimbabazi** [comment]
> @Thacien1 @mmindje
> 
> Thanks for the data file. Remember it is not necessary to add GBIF data to this file. That will be harvested directly from GBIF and served as optional data to add.
> 
> You should ony focus on the other bird datasets that you have for Rwanda.
> 
> ![image](https://user-images.githubusercontent.com/45286876/86438366-ae4da900-bd06-11ea-8618-a8eeeb643bcb.png)

Thanks @helendallas , information well noted!

**Comment by mmindje** [comment]
@helendallas may you organize for us a session to go through again the bird occurrence data template. We are confused on some issues that need clarification
Thank you

**Comment by helendallas** [comment]
@mmindje Sure no problem, I can manage at 14h00 today if that suits you.  

Please send me the bird data that you need to add to the template. so the following datasets from your DataSet Tracker.

Birds   from Mukungwa  and Lake Kivu catchments | D1
Lake   Gaharwa birds | D3

**Comment by mmindje** [comment]
Thank you @helendallas well, today we shall be having another staff meeting at the time.
Is that possible for we can do the meeting at 10h00 Am tomorrow?

The team shall attach the files as requested.

@DanielIgirimbabazi can you attach the data?
Thank you

**Comment by DanielIgirimbabazi** [comment]
[LakeKivu_Bird_2019_CoEB_Checklist_data.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4883937/LakeKivu_Bird_2019_CoEB_Checklist_data.xlsx)
[Rugezi lake&swamp_Birds_Checklist.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4883940/Rugezi.lake.swamp_Birds_Checklist.xlsx)
[Rwanda birding club_14 Feb 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4883942/Rwanda.birding.club_14.Feb.2020.xlsx)

Dear @helendallas , attached are the datasets we are preparing to add to the template.
FYI, about "Birds from Mukungwa" we would like to change the name to "Rugezi lake&swamp birds" as we noticed we had misplaced the name, so it would need to be corrected within dataset tracker as well.
Also, "Lake Gaharwa birds" are under the name "Rwanda birding club" from the files attached above.

**Comment by helendallas** [comment]
@mmindje Sorry I am not available tomorrow. Lets aim to go through it after our 10h00 RBIS meeting on thursday, we can remain on the  meeting as a smaller group and work through it. Thanks for the data, I will familiarise myself with it in the meanwhile.

**Comment by mmindje** [comment]
Yes, that is also fine @helendallas

**Comment by helendallas** [comment]
@mmindje @DanielIgirimbabazi @Thacien1 
I found a more recent checklist of A checklist by Gaël R. Vande weghe* | October 2018 using Google. Not sure if you are aware of this more recent publication. You might want to check this as well.
[Birds-of-Rwanda-GVande-weghe-2018.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4895287/Birds-of-Rwanda-GVande-weghe-2018.pdf)

**Comment by mmindje** [comment]
Hi @Thacien1, The attached file is the one I presented yesterday and can be used to develop the occurrence bird data
[RBIS.Bird.Data.2.July.2020 This one to be used.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4903392/RBIS.Bird.Data.2.July.2020.This.one.to.be.used.xlsx)

**Comment by mmindje** [comment]
Hello @helendallas , the screenshot here needs again some clarification
![image](https://user-images.githubusercontent.com/64961274/87288687-f9806c80-c4fb-11ea-85a6-34654a840910.png)

The Author (s) is this the original authority for the Birds or the author of the publication?

**Comment by helendallas** [comment]
@mmindje  You need to add the Author(s) when the  Reference Category is Peer-reviewed scientific article, report, thesis. Not needed for Database or unpublished data.

See 5 Managing citations and documents of the report I prepared for further details on managing metadata.

**Comment by Thacien1** [comment]
Dear @helendallas ,
Kindly receive the updated Bird data file the Biodiversity Data Management Team (BDMT) has been working on. 
We are looking forward for your comments. Thank you

[RBIS.Bird.Data.13.July.2020_ Data team edits.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4912522/RBIS.Bird.Data.13.July.2020_.Data.team.edits.xlsx)

**Comment by helendallas** [comment]
@Thacien1 
Almost there: I have done a few final edits and renamed the file:
**RBIS Bird Data 14 July 2020**

Some notes for this and future data files:

- Checked capitals for names - changed: Jean Pierre Vande **W**eghe and Gaël Ruboneka
- Author(s) need to be **Surname Initials**, so I have changed to **Vande Weghe JP and Ruboneka G**
- Year - this should be the year the report was published -  the one you have linked was **2018** not 2011. 
- Deleted abbreviation RBD in Rwanda Development Board as not necessary
- Source refers to the Thesis or report publisher or Database Name  - So for Database I have changed to **Rwanda Birding Club Checklist**
- Deleted Title for: Rwanda Bird checklist - this is for peer-reviewed scientific articles, published reports and thesis only
- Changed Reference Category of Rwanda Bird checklist to **Database** - since the data is not published as a report (facebook page is not adequate)
- Notes added do not add value (you have already specified visual observation for example - notes should be about the data point e.g. immature,  pupa, sampling period, or details, etc. I have added instead that for 2011, montn and day not specified

I am checking with DImas re confirmation of details on the columns that need to be filled for each type of Reference Category . I will add to this ticket once I have them.  

[RBIS Bird Data 14 July 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4917887/RBIS.Bird.Data.14.July.2020.xlsx)

**Comment by Thacien1** [comment]
> @Thacien1
> Almost there: I have done a few final edits and renamed the file:
> **RBIS Bird Data 14 July 2020**
> 
> Some notes for this and future data files:
> 
> * Checked capitals for names - changed: Jean Pierre Vande **W**eghe and Gaël Ruboneka
> * Author(s) need to be **Surname Initials**, so I have changed to **Vande Weghe JP and Ruboneka G**
> * Year - this should be the year the report was published -  the one you have linked was **2018** not 2011.
> * Deleted abbreviation RBD in Rwanda Development Board as not necessary
> * Source refers to the Thesis or report publisher or Database Name  - So for Database I have changed to **Rwanda Birding Club Checklist**
> * Deleted Title for: Rwanda Bird checklist - this is for peer-reviewed scientific articles, published reports and thesis only
> * Changed Reference Category of Rwanda Bird checklist to **Database** - since the data is not published as a report (facebook page is not adequate)
> * Notes added do not add value (you have already specified visual observation for example - notes should be about the data point e.g. immature,  pupa, sampling period, or details, etc. I have added instead that for 2011, montn and day not specified
> 
> I am checking with DImas re confirmation of details on the columns that need to be filled for each type of Reference Category . I will add to this ticket once I have them.
> 
> [RBIS Bird Data 14 July 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4917887/RBIS.Bird.Data.14.July.2020.xlsx)

Thank you @helendallas for the comments and advises on future data files. 

Best, Thacien

**Comment by helendallas** [comment]
@mmindje @Thacien1 @DanielIgirimbabazi 

For the bird data file, I have simply deleted the species names, as the taxon is what is used for ingesting data.

Revised file attached.

[RBIS Bird Data 14 July 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5136508/RBIS.Bird.Data.14.July.2020.xlsx)

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi
> 
> For the bird data file, I have simply deleted the species names, as the taxon is what is used for ingesting data.
> 
> Revised file attached.
> 
> [RBIS Bird Data 14 July 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5136508/RBIS.Bird.Data.14.July.2020.xlsx)

Noted. Thank you so much

**Comment by helendallas** [comment]
Thanks team - final Bird data file:

[RBIS Bird Data 2020_09_22 Final for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5267600/RBIS.Bird.Data.2020_09_22.Final.for.RBIS.V1.xlsx)

**Comment by mmindje** [comment]
Hi @Thacien1 and @DanielIgirimbabazi , we  have two data source for birds that we will need to work on.
E-mail with a check list from Birding tour company and also the document sent to us from Beth.

I have reopened the issue for us to make some follow up!

However for some data set there. the birds are terrestrial: Assessment of threatened terrestrial bird species in Rwanda. So we hall look a these after the release of the V1. Stay alerted!

**Comment by helendallas** [comment]
@mmindje Sounds good. 

Can I suggest you create a new ticket that specifically mentions the new bird data and then close this one. Normally each data source gets its own ticket so that it is easy to keep track of the data work flows.
