### ISSUE TITLE
Check Google Scholar for additional bird data

### ISSUE THREAD

**Issue by helendallas** [mmindje/Data-management-FRC-RBIS#14]
@mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu 

I wanted to encourage you to search using Google Scholar to discover additional Bird related publications that could be added to your Bird data file. 

The RBIS design allows for data tracking over time, and one of the indicators of biodiversity includes how bird populations have changed over time.  It is thus useful to include additional data points of bird observations from publications when the location (including georeference) is provided.  

I attach some papers I found on Google Scholar.  I have not evaluated their usefulness or geographic context -  I merely wanted to demonstrate the importance of exploring alternative sources of data.
[Boedts_2016 Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918847/Boedts_2016.Rwanda.pdf)
[Derhe et al 2020 status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918848/Derhe.et.al.2020.status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf)
[Fain 1993.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918852/Fain.1993.pdf)
[Gatali&Kjell-bird diversity-Akagera-2015 published.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918853/Gatali.Kjell-bird.diversity-Akagera-2015.published.pdf)
[Gatesire 2012.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918857/Gatesire.2012.pdf)
[Gatesire et al 2014.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918861/Gatesire.et.al.2014.pdf)
[Higg & Vande weghe2 A response to Gatali and Wallin 2015 Bird diversity.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918864/Higg.Vande.weghe2.A.response.to.Gatali.and.Wallin.2015.Bird.diversity.pdf)
[KANYAMIBWA Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918869/KANYAMIBWA.Rwanda.pdf)

[Nsabagasani et al 2008_Akanyura_Wetland_Survey_Rwanda_0.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918844/Nsabagasani.et.al.2008_Akanyura_Wetland_Survey_Rwanda_0.pdf)

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu
> 
> I wanted to encourage you to search using Google Scholar to discover additional Bird related publications that could be added to your Bird data file.
> 
> The RBIS design allows for data tracking over time, and one of the indicators of biodiversity includes how bird populations have changed over time. It is thus useful to include additional data points of bird observations from publications when the location (including georeference) is provided.
> 
> I attach some papers I found on Google Scholar. I have not evaluated their usefulness or geographic context - I merely wanted to demonstrate the importance of exploring alternative sources of data.
> [Boedts_2016 Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918847/Boedts_2016.Rwanda.pdf)
> [Derhe et al 2020 status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918848/Derhe.et.al.2020.status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf)
> [Fain 1993.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918852/Fain.1993.pdf)
> [Gatali&Kjell-bird diversity-Akagera-2015 published.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918853/Gatali.Kjell-bird.diversity-Akagera-2015.published.pdf)
> [Gatesire 2012.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918857/Gatesire.2012.pdf)
> [Gatesire et al 2014.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918861/Gatesire.et.al.2014.pdf)
> [Higg & Vande weghe2 A response to Gatali and Wallin 2015 Bird diversity.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918864/Higg.Vande.weghe2.A.response.to.Gatali.and.Wallin.2015.Bird.diversity.pdf)
> [KANYAMIBWA Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918869/KANYAMIBWA.Rwanda.pdf)
> 
> [Nsabagasani et al 2008_Akanyura_Wetland_Survey_Rwanda_0.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918844/Nsabagasani.et.al.2008_Akanyura_Wetland_Survey_Rwanda_0.pdf)

Dear @helendallas , Thank you so much for this perfect comment. We will also do the same for the remaining taxa. Message has noted well with many thanks. 

Warm regards,
Thacien

**Comment by DanielIgirimbabazi** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu
> 
> I wanted to encourage you to search using Google Scholar to discover additional Bird related publications that could be added to your Bird data file.
> 
> The RBIS design allows for data tracking over time, and one of the indicators of biodiversity includes how bird populations have changed over time. It is thus useful to include additional data points of bird observations from publications when the location (including georeference) is provided.
> 
> I attach some papers I found on Google Scholar. I have not evaluated their usefulness or geographic context - I merely wanted to demonstrate the importance of exploring alternative sources of data.
> [Boedts_2016 Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918847/Boedts_2016.Rwanda.pdf)
> [Derhe et al 2020 status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918848/Derhe.et.al.2020.status_diversity_and_trends_of_the_bird_communities_in_volcanoes_national_park_and_surrounds_rwanda.pdf)
> [Fain 1993.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918852/Fain.1993.pdf)
> [Gatali&Kjell-bird diversity-Akagera-2015 published.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918853/Gatali.Kjell-bird.diversity-Akagera-2015.published.pdf)
> [Gatesire 2012.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918857/Gatesire.2012.pdf)
> [Gatesire et al 2014.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918861/Gatesire.et.al.2014.pdf)
> [Higg & Vande weghe2 A response to Gatali and Wallin 2015 Bird diversity.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918864/Higg.Vande.weghe2.A.response.to.Gatali.and.Wallin.2015.Bird.diversity.pdf)
> [KANYAMIBWA Rwanda.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918869/KANYAMIBWA.Rwanda.pdf)
> 
> [Nsabagasani et al 2008_Akanyura_Wetland_Survey_Rwanda_0.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/4918844/Nsabagasani.et.al.2008_Akanyura_Wetland_Survey_Rwanda_0.pdf)

Thank you for this great tip @helendallas , we are going to put it into consideration indeed!
Regards,
Daniel
