### ISSUE TITLE
Process for adding Study reference/metadata into Data files for ingestion to RBIS

### ISSUE THREAD

**Issue by helendallas** [mmindje/Data-management-FRC-RBIS#15]
@mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu 

For guidance about adding information to columns related to the Study Reference, please find details below. When adding the following, these columns need to be populated:

**Peer-reviewed scientific article**
Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title;  DOI or URL (if DOI is not available)
For  **Peer-reviewed scientific article** the Source is the **Journal**
For **Peer-reviewed scientific article** the Title is the title of the article.

**Published report**
Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title;  URL or Document Upload Link. Note the Document Upload Link is obtained after the report is added to RBIS. I will go through this process with you  once RBIS is up and ready to use.
 
**Thesis**
Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title;  URL or Document Upload Link
 
**Database**
Collector/Owner; Collector/Owner Institute; Author(s); Year; Source
 
**Unpublished data**
Collector/Owner; Collector/Owner Institute; Author(s); Year; Source

Do not provide a Title is the data are unpublished

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu
> 
> For guidance about adding information to columns related to the Study Reference, please find details below. When adding the following, these columns need to be populated:
> 
> **Peer-reviewed scientific article**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; DOI or URL (if DOI is not available)
> 
> **Published report**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; URL or Document Upload Link. Note the Document Upload Link is obtained after the report is added to RBIS. I will go through this process with you once RBIS is up and ready to use.
> 
> **Thesis**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; URL or Document Upload Link
> 
> **Database**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source
> 
> **Unpublished data**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source

Alright. Thank you so much dear @helendallas .

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi @Deborahcyu
> 
> For guidance about adding information to columns related to the Study Reference, please find details below. When adding the following, these columns need to be populated:
> 
> **Peer-reviewed scientific article**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; DOI or URL (if DOI is not available)
> 
> **Published report**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; URL or Document Upload Link. Note the Document Upload Link is obtained after the report is added to RBIS. I will go through this process with you once RBIS is up and ready to use.
> 
> **Thesis**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source; Title; URL or Document Upload Link
> 
> **Database**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source
> 
> **Unpublished data**
> Collector/Owner; Collector/Owner Institute; Author(s); Year; Source

Alright. Thank you so much dear @helendallas .
