### ISSUE TITLE
Create Amphibian Master list

### ISSUE THREAD

**Issue by helendallas** [mmindje/Data-management-FRC-RBIS#17]
We need to create a master list for anurans

**Comment by mmindje** [comment]
@DanielIgirimbabazi, @Thacien1 and @Deborahcyu
Find attached the Anurans mater list ready 

@helendallas we are still working on the file; after you have some times, we can discuss on the data (Origin and Endemism)...just to have the information right AND **DISCUSS ON THE RENAMING OF THIS MODULE**

[RBIS.Master.List.of.Taxa_Amphibians_BDMT_21.Sept.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5256467/RBIS.Master.List.of.Taxa_Amphibians_BDMT_21.Sept.2020.xlsx)

**Comment by helendallas** [comment]
@mmindje Lets chat about this tomorrow at our meeting. Thanks

**Comment by mmindje** [comment]
> @mmindje Lets chat about this tomorrow at our meeting. Thanks

sure Helen, glad to hear that you gonna there!

**Comment by Thacien1** [comment]
Here is **RBIS** *_* **Amphibians**_ **Master** **List** updated file.

Thank you.

[RBIS.Master.List.of.Taxa_Amphibians_BDMT 1 October 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5310484/RBIS.Master.List.of.Taxa_Amphibians_BDMT.1.October.2020.xlsx)

**Comment by helendallas** [comment]
@Thacien1 This looks great, a few minor edits. I am testing the upload into the staging site to check if there are any issues.


[Uploading RBIS Amphibian data 2020_10_01 final for RBIS V1.xlsx…]()

**Comment by Thacien1** [comment]
> @Thacien1 This looks great, a few minor edits. I am testing the upload into the staging site to check if there are any issues.
> 
> Uploading RBIS Amphibian data 2020_10_01 final for RBIS V1.xlsx…

Thank you   @helendallas

**Comment by helendallas** [comment]
@Thacien1 Three taxa with errors. Please cam you check. I noted the last one has a link to a different taxon on GBIF, and should be changed to No..

Amietia nutti
Sclerophrys kisoloensis
Sclerophrys regularis

File attached - taxa highlighted. Please use this file for any edits. Thanks

[RBIS Amphibian data 2020_10_01 final for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5316250/RBIS.Amphibian.data.2020_10_01.final.for.RBIS.V1.xlsx)

**Comment by helendallas** [comment]
@Thacien1 I just reimported and it all worked, after I changed the Sclerophrys regularis to No on GBIF.

Please confirm this is acceptable. Thanks

**Comment by Thacien1** [comment]
> @Thacien1 I just reimported and it all worked, after I changed the Sclerophrys regularis to No on GBIF.
> 
> Please confirm this is acceptable. Thanks

Dear @helendallas , 
Consider this attached file as final **Amphibians** **MasterList** file.  We have double checked the file and fixed all mistakes ( Firstly, **Sclerophrys regularis** is not found in **GBIF** and its common name is **African common toad**  not Common African  toad, and then a typo error of **Amietia** **nutti**'s Family name) . We have also successfully tested the file on RBIS staging site. 

Thank you.

[RBIS.Amphibian.data.2020_10_01.final.for.RBIS.V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5317018/RBIS.Amphibian.data.2020_10_01.final.for.RBIS.V1.xlsx)

**Comment by helendallas** [comment]
@Thacien1 Thanks. I actually asked Dimas to delete all dataso that I could test the uploading as we need to create a different type of csv file. I was wondering where the amphibian data came from as I had not uploaded it.  I will need to check though as there are to many records.

Please check before adding anything to staging or live in future thanks.

I am preparing documentation to outline the process.

**Comment by Thacien1** [comment]
> @Thacien1 Thanks. I actually asked Dimas to delete all dataso that I could test the uploading as we need to create a different type of csv file. I was wondering where the amphibian data came from as I had not uploaded it. I will need to check though as there are to many records.
> 
> Please check before adding anything to staging or live in future thanks.
> 
> I am preparing documentation to outline the process.

Thank you @helendallas . This is noted.
