### ISSUE TITLE
Amphibian module's Logo

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#19]

**Comment by mmindje** [comment]
The amphibian logo
@helendallas , we can choose between these
![a-sitting-green-frog-on-a-white-background-vector-23886687](https://user-images.githubusercontent.com/64961274/94787048-0d888b80-03d2-11eb-9315-0667a8c62139.jpg)
![72-729213_tree-frog-silhouette-clipart-png-download-tree-frog](https://user-images.githubusercontent.com/64961274/94787120-22fdb580-03d2-11eb-9dd4-7c08447e6439.png)

**Comment by helendallas** [comment]
Thanks, light on dark is better as it will work with the other logos. Lest try the first one then

**Comment by helendallas** [comment]
@mmindje I checked and the first one doesnt work - opting to use the second as it is more striking. Here is what they look like on RBIS staging. 

![image](https://user-images.githubusercontent.com/45286876/94808296-39ffd000-03f1-11eb-9019-7bd4675fae07.png)

![image](https://user-images.githubusercontent.com/45286876/94809622-2bb2b380-03f3-11eb-93b4-715e979ba58e.png)

**Comment by mmindje** [comment]
@helendallas yes, I find the second also better than the first for sure!
Thank you Helen!

**Comment by helendallas** [comment]
@mmindje I checked on the site, and the logo needs a white background, and need to be larger if possible

![image](https://user-images.githubusercontent.com/45286876/94814394-8fd87600-03f9-11eb-9a9d-87f904a7649c.png)

**Comment by mmindje** [comment]
do you mean, I look for other silhouettes?

I am suggesting more: 
![black-silhouette-cute-smiling-frog-sitting-on-vector-31544544](https://user-images.githubusercontent.com/64961274/94832125-cddf9500-040d-11eb-9e0c-07c05a7f5011.jpg)


![istockphoto-695789496-612x612](https://user-images.githubusercontent.com/64961274/94830887-55c49f80-040c-11eb-9162-1dc89b4fad24.jpg)

![67-678684_frog-vector-tribal-frog-silhouette](https://user-images.githubusercontent.com/64961274/94832163-dc2db100-040d-11eb-96ac-64fd1d37618f.jpg)
