### ISSUE TITLE
Birds' Module Logo 

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#20]

**Comment by mmindje** [comment]
@helendallas I am suggesting the logo as following:
![dove-clipart-animated-4](https://user-images.githubusercontent.com/64961274/94786329-1c227300-03d1-11eb-9e29-5a22cbef07ff.png)
![images](https://user-images.githubusercontent.com/64961274/94786335-1dec3680-03d1-11eb-8fea-6b94af5e6685.jpg)

**Comment by helendallas** [comment]
Okay - the first, simpler one should be fine.

**Comment by mmindje** [comment]
I hope it will also be visible on the white! @helendallas

**Comment by helendallas** [comment]
Yes, it may not show up that well. I guess a solid log would be better
