### ISSUE TITLE
Trainings needed

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#21]
Dear @helendallas 

**We had a discussion among us and we suggested some points where we will need some improvement (training). However, we intend to have these upon your own time or schedule.** 

Suggestion for Training

**1. How to delete a file from the RBIS?**
I case we realize there is a mistake.

**2. How to update the existing module?**
You told us about this but we also need to view the processes.

**3. Harvesting data from GBIF**
Having a clue about what it takes.

**4. Adding silhouette on modules**
Last time you requested for frogs and birds silhouettes to be added to the modules.

**5. Removal of duplicates**
For data cleaning prior to uploading to the system

Thank you

**Comment by mmindje** [comment]
Hellen sent us a document with everything's we need so far to manage data

**Comment by mmindje** [comment]
Document sent to us frim Hellen 
[Uploading Administration guidelines for RBIS 2020 10 30.pdf…]()

**Comment by helendallas** [comment]
Closing this ticket as training mentioned has been done.
