### ISSUE TITLE
Adding species images to the species display 

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#27]
@helendallas I saw an image displayed for _Afrixalus quadrivittatus_ and was thinking if there is a way to upload images for the rest or those which do not have images; just a suggestion

![image](https://user-images.githubusercontent.com/64961274/97703528-72123580-1ab9-11eb-9be2-4952aaa9e48e.png)

for others

![image](https://user-images.githubusercontent.com/64961274/97703127-c0730480-1ab8-11eb-9c6d-f6523c8d3800.png)

**Comment by helendallas** [comment]
@mmindje At the moment the only images displayed are those available on GBIF. This is something we would need to discuss with Tim and Dimas.

**Comment by helendallas** [comment]
@mmindje This is a ticket for the Kartoza RBIS project. As far as I know Dimas is working on this. 

See Upload and manage taxon images #2580

Closing this ticket as it is development, not data mobilisation.
