### ISSUE TITLE
Landing page story about anurans 

### ISSUE THREAD

**Issue by bakaplin** [mmindje/Data-management-FRC-RBIS#28]
Shift this story to NEWS tab on top of landing page:

Benefits of Frogs

Anurans (Frogs and Toads) are known excellent bioindicators of ecosystem health such as wetlands where their populations’ survival is constituted. However, studies on...

**Comment by Thacien1** [comment]
Thank you Prof. Beth,
Celestin will assist

**Comment by bimeobed** [comment]
Many thanks, Prof. Beth,
