### ISSUE TITLE
Checking coordinates outside Rwandan boundaries

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#31]
Hi @bimeobed , @Thacien1 and @DanielIgirimbabazi 

I wanted us to see why are these coordinates following outside the admin boundaries of Rwanda.

In fact we got the data saying they are in the Virunga National Park but we realized that the coordinates are outside of Rwanda.

Follow this link to get the insight: 

![image](https://user-images.githubusercontent.com/64961274/99797482-019a8980-2b38-11eb-989b-c4f7d4ef683d.png)

https://rbis.ur.ac.rw/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=%5B%5D&modules=8&validated=&sourceCollection=%5B%22RBIS%22%5D&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=%5B%5B29.494119286537167,-1.4401695324158794%5D,%5B29.4921612739563,-1.442598844861422%5D,%5B29.493083953857422,-1.4446581275522732%5D,%5B29.495041966438297,-1.4449530767432464%5D,%5B29.49638307094574,-1.4405985502547054%5D,%5B29.49550867080688,-1.439681524526037%5D,%5B29.494119286537167,-1.4401695324158794%5D%5D

**Comment by mmindje** [comment]
the area is for the following credentials:

-00607
Site Description
Gasindikira
Site Coordinates
29.547, -1.399

**Comment by mmindje** [comment]
@bimeobed check if the administrative boundaries are not a problem.!

**Comment by bimeobed** [comment]
Thank you Mapendo for sure the data are outside of Rwanda for Ngezi wetland
and Gasindikira wetland the error made is for coordinate from Karisoke so
to solve this we need to push the coordinate or we can take one day to go
on  the field to collect the accurate data.
[image: image.png]
[image: image.png]
*Obed BIMENYIMANA*
*GIS And Remote Sensing User*
*CGIS-UR Professional Intern*
*Tel: +250789860442*
*Email:bimeobed@gmail.com <Email%3Abimeobed@gmail.com>*
