### ISSUE TITLE
Coordinates outside Rwandan boundaries sorted out

### ISSUE THREAD

**Issue by Thacien1** [mmindje/Data-management-FRC-RBIS#32]

**Comment by Thacien1** [comment]
Dear @helendallas and @mmindje 

Here is an **updated amphibians occurrence data file** after removing the coordinates which fall outside the Rwandan boundaries. We suggest that it  can be ingested into RBIS to replace the existing one.
[RBIS Amphibian Data 2020_11_25 Final for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5597416/RBIS.Amphibian.Data.2020_11_25.Final.for.RBIS.V1.xlsx)




Thank you

**Comment by helendallas** [comment]
Merged with #29
