### ISSUE TITLE
Check GBIF_Birds data that fall outside of Rwanda

### ISSUE THREAD

**Issue by Thacien1** [mmindje/Data-management-FRC-RBIS#36]

**Comment by Thacien1** [comment]
Dear @helendallas some of GBIF_Birds data fall out side of Rwanda. We think that Dimas can help to sort out this issue. 

More of data fall outside and you can view it when you check the GBIF data.

![image](https://user-images.githubusercontent.com/65008258/101327498-6fa0b980-3877-11eb-8d86-b705afc3d9b9.png)

Thank you

**Comment by mmindje** [comment]
incredible! I think GBIF data are automated as they are harvested from their portal
Let's hope something can be done to correct it!

Thank you @Thacien1 for the follow up!

**Comment by helendallas** [comment]
Ticket created for DImas
Please decrease the buffer around Rwanda country border to exclude non-Rwandan GBIF records #2447
