### ISSUE TITLE
Macroinvertebrate data file_ Current Tasks

### ISSUE THREAD

**Issue by Thacien1** [mmindje/Data-management-FRC-RBIS#38]

**Comment by Thacien1** [comment]
Dear @Deborahcyu could you work on UUDID column please? @mmindje and @DanielIgirimbabazi let us meet on tomorrow and Friday and work on geographic coordinate cleaning and Date format.

Thank you so much.

**Comment by mmindje** [comment]
Sure, thank you

**Comment by helendallas** [comment]
I am picking up quite a few issues. Please make sure you follow all the checks laid out in the admin guidelines doc,  I have gone through the file and made changes in red.

For example:
I added the river name to the Original Wetland Name column
I changed down stream to downstream, up stream to upstream
There are several spelling errors – these need to be checked once the corrected master list is done.
Present must always be "1"
Author format is incorrect
The Reference category is Peer-reviewed scientific article not Published report
If you have a DOI then you don’t need a URL as well.
DOI should only be the numbers: 10.1007/s10661-019-7226-5

[Administration guidelines for RBIS 2020 10 30.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/5873592/Administration.guidelines.for.RBIS.2020.10.30.pdf)

**Comment by helendallas** [comment]
[RBIS_Macroinvertebrate.final.2021. HDxlsx.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5873622/RBIS_Macroinvertebrate.final.2021.HDxlsx.xlsx)

Here is the start of the revision, thanks

**Comment by Thacien1** [comment]
> I am picking up quite a few issues. Please make sure you follow all the checks laid out in the admin guidelines doc, I have gone through the file and made changes in red.
> 
> For example:
> I added the river name to the Original Wetland Name column
> I changed down stream to downstream, up stream to upstream
> There are several spelling errors – these need to be checked once the corrected master list is done.
> Present must always be "1"
> Author format is incorrect
> The Reference category is Peer-reviewed scientific article not Published report
> If you have a DOI then you don’t need a URL as well.
> DOI should only be the numbers: 10.1007/s10661-019-7226-5
> 
> [Administration guidelines for RBIS 2020 10 30.pdf](https://github.com/mmindje/Data-management-FRC-RBIS/files/5873592/Administration.guidelines.for.RBIS.2020.10.30.pdf)



Dear @helendallas , 

Thank you so much for the comments. We will notice this in the future. 
We are going to work on the comments and will get back to you as soon as possible. 

Regards,

Thacien
