### ISSUE TITLE
Revise Site descriptions for GBIF sites

### ISSUE THREAD

**Issue by helendallas** [mmindje/Data-management-FRC-RBIS#44]
As discussed previously in our meetings, several site descriptions (termed localities in GBIF) do not accurately reflect the current names in Rwanda.

There are however, over 30,000 sites from GBIF.  The RBIS team need to decide if it is feasible to revise all of the Site Descriptions

![image](https://user-images.githubusercontent.com/45286876/116045855-c108e400-a672-11eb-87b9-1e9867e2901b.png)

If the team decides this needs to be done, then it can be done using the Data/Site Visits, and select Source Collection = GBIF, then edit each site description

![image](https://user-images.githubusercontent.com/45286876/116046213-24931180-a673-11eb-86f5-82329a535559.png)

![image](https://user-images.githubusercontent.com/45286876/116046409-55734680-a673-11eb-8e91-fa35ee889bdc.png)

**Comment by helendallas** [comment]
See also ticket on Kartoza project:

Revise GBIF Site descriptions to reflect correct Rwandan names #2510

**Comment by mmindje** [comment]
I gues they are now okay as we are using the updated base map @bimeobed is that right?

**Comment by helendallas** [comment]
I suggest we close this ticket as it is not possible to update GBIF site descriptions as they will be overwritten once data are harvested again from GBIF

**Comment by bimeobed** [comment]
@mmindje now it ok . You are right
