### ISSUE TITLE
Populate Birds Data Master list

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#5]

**Comment by mmindje** [comment]
We need to know how to fill the remaining fields @helendallas . An email has been sent with the filled templates with the right side of columns empty. We need assistance

Here is a screenshot of the right part of the template
![master list fields](https://user-images.githubusercontent.com/64961274/84575345-b623c880-adac-11ea-8123-657e9b957e74.JPG)

**Comment by helendallas** [comment]
First step is to take the GBIF Bird species I sent you - attached here - and extract and edit into the correct columns on the Master List of Bird Taxa.xls.   You also need to assign the taxonomic rank to each. species (most will be species for birds).

See here to get the GBIF link for each species:
![image](https://user-images.githubusercontent.com/45286876/84627206-c17b0f00-aee6-11ea-9ab8-968cb282fc75.png)

You type in the scientific name of each species and the get to the GBIF page:
https://www.gbif.org/species/9127087

All species from data sets D1 and D3, also need to be included in the Master List of Bird Species. You can check the taxonomic backbone on GBIF to populate the taxon hierarchy.  Check using the classification search:

Origin refers to whether a species is native or non-native, in other words whether it would naturally occur in Rwanda or not. This is really important for fish species, but in all likelihood all birds will be native. You should check online what else you can find out.

Endemism  refers to whether a species only occurs in Rwanda - see descriptions in Data Management document 3.1.1.

Conservation status: You need to check on the IUCN Threatened species database. If Rwanda has an updated list, then you can use this, otherwise you need to populate this column for each species by searching on the IUCN website.  Many may be "Not evaluated". 
https://www.iucnredlist.org/

I also recall you saying you needed to add "Local name". I suggest you include this after 
Scientific name and authority by adding a new column.

@mmindje @Thacien1 Please read the above. We can have a zoom session on this is you think it is necessary

**Comment by mmindje** [comment]
Thank you @helendallas 
The team lead by @Thacien1 is working in the master list to fill in the remaining information

**Comment by mmindje** [comment]
We have set a deadline on Tuesday 23rd June to have the master list ready. What will be missing are the local names. @mmindje IS TO LOOK FOR THIS with local birds experts and the rest of the team working on the remaining columns

**Comment by Thacien1** [comment]
Thank you @helendallas. The team is working on this.

**Comment by Thacien1** [comment]
> First step is to take the GBIF Bird species I sent you - attached here - and extract and edit into the correct columns on the Master List of Bird Taxa.xls. You also need to assign the taxonomic rank to each. species (most will be species for birds).
> 
> See here to get the GBIF link for each species:
> ![image](https://user-images.githubusercontent.com/45286876/84627206-c17b0f00-aee6-11ea-9ab8-968cb282fc75.png)
> 
> You type in the scientific name of each species and the get to the GBIF page:
> https://www.gbif.org/species/9127087
> 
> All species from data sets D1 and D3, also need to be included in the Master List of Bird Species. You can check the taxonomic backbone on GBIF to populate the taxon hierarchy. Check using the classification search:
> 
> Origin refers to whether a species is native or non-native, in other words whether it would naturally occur in Rwanda or not. This is really important for fish species, but in all likelihood all birds will be native. You should check online what else you can find out.
> 
> Endemism refers to whether a species only occurs in Rwanda - see descriptions in Data Management document 3.1.1.
> 
> Conservation status: You need to check on the IUCN Threatened species database. If Rwanda has an updated list, then you can use this, otherwise you need to populate this column for each species by searching on the IUCN website. Many may be "Not evaluated".
> https://www.iucnredlist.org/
> 
> I also recall you saying you needed to add "Local name". I suggest you include this after
> Scientific name and authority by adding a new column.
> 
> @mmindje @Thacien1 Please read the above. We can have a zoom session on this is you think it is necessary

**Comment by Thacien1** [comment]
Dear @helendallas , we (team) are working on  this. Hope to get back to you by tomorrow.

Thank you

**Comment by helendallas** [comment]
@Thacien1 Perhaps you can give us an update and share your screen at todays meeting @09h00.

**Comment by helendallas** [comment]
Rema Bird Document - Team to refer to it.  @mmindje to obtain from Beth 
@mmindje you should add elias and beth to the repository so we can tag them for speciefic requests

**Comment by helendallas** [comment]
Notes from RBIS Bird Master list discussion:

For RBIS   team
1. Only one record (row) per species on   the master list
2. Check if species is on GBIF: yes/No;   If No, then just include taxanomic hierarchy
3. Add GBIF Link GBIF for each species   (https://www.gbif.org/species/2480610)
4. Change source to the actual study   reference, source of the data e.g. checklist
5. Add Scientific authority copied from   GBIF page e.g. Accipiter badius (Gmelin, 1788)
6. Copy species into Taxon column for all species
7. Check taxon rank - change if necessary
8. Populate Origin using dropdown list
9. Populate Endemisms using dropdown list
10. Populate Conservation status using   dropdown list
11. Populate Common Name
12. Populate Rwandan Name
13. Populate French Name

**Comment by helendallas** [comment]
@revised excel file of Master list of bird species attached - and also sent by email to @Thacien1 @mmindje 

[RBIS Master List of Taxa_Birds_BDMT.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4812096/RBIS.Master.List.of.Taxa_Birds_BDMT.xlsx)

**Comment by mmindje** [comment]
I think now @DanielIgirimbabazi can join

**Comment by DanielIgirimbabazi** [comment]
Happy to join, let's get things done!

**Comment by mmindje** [comment]
> Notes from RBIS Bird Master list discussion:
> 
> For RBIS team
> 
> 1. Only one record (row) per species on   the master list
> 2. Check if species is on GBIF: yes/No;   If No, then just include taxanomic hierarchy
> 3. Add GBIF Link GBIF for each species   (https://www.gbif.org/species/2480610)
> 4. Change source to the actual study   reference, source of the data e.g. checklist
> 5. Add Scientific authority copied from   GBIF page e.g. Accipiter badius (Gmelin, 1788)
> 6. Copy species into Taxon column for all species
> 7. Check taxon rank - change if necessary
> 8. Populate Origin using dropdown list
> 9. Populate Endemisms using dropdown list
> 10. Populate Conservation status using   dropdown list
> 11. Populate Common Name
> 12. Populate Rwandan Name
> 13. Populate French Name

Yes. This is very clear now @helendallas

**Comment by mmindje** [comment]
@DanielIgirimbabazi, @Thacien1 and @Deborahcyu this link will help us get our shared task https://drive.google.com/drive/folders/1eCv_-VkWGnmLDCMzmeGnWPts-FPT9IpS

**Comment by helendallas** [comment]
@Thacien1 Please also check the taxonomy all the way from Kingdom to species in your Master list, and change it to match GBIF if different - spelling is important and the higher taxonomy should match what is on GBIF.  For genus you just need the actual genus not the scientific authority as well.

![image](https://user-images.githubusercontent.com/45286876/85368727-12fd4c80-b52c-11ea-8457-6f830d0aebff.png)

**Comment by Thacien1** [comment]
> @Thacien1 Please also check the taxonomy all the way from Kingdom to species in your Master list, and change it to match GBIF if different - spelling is important and the higher taxonomy should match what is on GBIF. For genus you just need the actual genus not the scientific authority as well.
> 
> ![image](https://user-images.githubusercontent.com/45286876/85368727-12fd4c80-b52c-11ea-8457-6f830d0aebff.png)

Excellent! Thank you so much @helendallas

**Comment by Thacien1** [comment]
Thank you @helendallas , 
This is excellent!

**Comment by mmindje** [comment]
@DanielIgirimbabazi look at the ticket #5 to compare with the information already in the google sheet

**Comment by Thacien1** [comment]
> @DanielIgirimbabazi look at the ticket #5 to compare with the information already in the google sheet

Thank you @mmindje

**Comment by mmindje** [comment]
@helendallas , the team has already made the attached Birds Master List but still three columns *(Synonyms, old scientific names and Kinyarwanda names) still pending for reasons we shall need to discuss in our meeting today at 9hAM.

**File:** [RBIS.Master.List.of.Taxa_Birds_BDMT on 26June 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4844226/RBIS.Master.List.of.Taxa_Birds_BDMT.on.26June.2020.xlsx)

**Comment by Thacien1** [comment]
Hello Team, The attached is the final RBIS filled master-list for Birds on 29 June 2020. The remaining field is for Kinyarwanda names. 

[RBIS.Master.List.of.Taxa_Birds_BDMT.on.1July.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4856446/RBIS.Master.List.of.Taxa_Birds_BDMT.on.1July.2020.xlsx)

**Comment by mmindje** [comment]
perfect thank you @Thacien1

**Comment by mmindje** [comment]
Thank you a lot @Thacien1 we should incorporate the bids names in Kinyarwanda
Check the attachment below: @DanielIgirimbabazi may you go ahead and add the Kinyarwanda names, if you get some times or if not, let me know to also get sometimes.
[Kinyarwanda bird names.docx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4850930/Kinyarwanda.bird.names.docx)

**Comment by helendallas** [comment]
@mmindje @Thacien1 Please can you kindly share the Final Bird Master List so that I can check it and we can forward to Dimas. Thanks

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 Please can you kindly share the Final Bird Master List so that I can check it and we can forward to Dimas. Thanks

Dear @helendallas , kindly receive the Final Bird Master List file. 
Warm regards,
Thacien
[Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4896191/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx)

**Comment by helendallas** [comment]
@mmindje @Thacien1 @DanielIgirimbabazi 

I realised when I was looking at the OdonataMap data that the way you have added the species in incorrect, and it please needs to be fixed in the bird master, bird data, odonata master and odonata data files.

The Genus and species need to be in separate columns. The taxon is the combination.  so for example:

**It should be:**

Genus     | Species |  Taxon
Accipiter | badius  |   Accipiter badius

**Not**
Genus     | Species                |  Taxon
                       | Accipiter badius  |   Accipiter badius

The taxon column is what is used when the data is ingested into RBIS.

I am attaching the Bird master file to show you how it needs to be changed.  
Please can you work towards correcting these and then note for the next groups you tackle. Thanks

[Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5136495/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx)

Please ask if not clear.

**Comment by Thacien1** [comment]
> @mmindje @Thacien1 @DanielIgirimbabazi
> 
> I realised when I was looking at the OdonataMap data that the way you have added the species in incorrect, and it please needs to be fixed in the bird master, bird data, odonata master and odonata data files.
> 
> The Genus and species need to be in separate columns. The taxon is the combination. so for example:
> 
> **It should be:**
> 
> Genus | Species | Taxon
> Accipiter | badius |   Accipiter badius
> 
> **Not**
> Genus | Species | Taxon
> | Accipiter badius | Accipiter badius
> 
> The taxon column is what is used when the data is ingested into RBIS.
> 
> I am attaching the Bird master file to show you how it needs to be changed.
> Please can you work towards correcting these and then note for the next groups you tackle. Thanks
> 
> [Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5136495/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.9July.2020.xlsx)
> 
> Please ask if not clear.

Thank you so much @helendallas . Let us work on them.

>

**Comment by Thacien1** [comment]
Final Bird master file. Species column cleaned.

[Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.28 Aug.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5140900/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.28.Aug.2020.xlsx)

**Comment by helendallas** [comment]
@Thacien1 
Thank. I found a few editorial issues that I have corrected and then I noticed one duplicate. Highlighted. PLease check. Thanks

Here is the edited file:
[Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3 Sep.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5167043/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3.Sep.2020.xlsx)

**Comment by Thacien1** [comment]
> @Thacien1
> Thank. I found a few editorial issues that I have corrected and then I noticed one duplicate. Highlighted. PLease check. Thanks
> 
> Here is the edited file:
> [Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3 Sep.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5167043/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3.Sep.2020.xlsx)

**Comment by Thacien1** [comment]
> > @Thacien1
> > Thank. I found a few editorial issues that I have corrected and then I noticed one duplicate. Highlighted. PLease check. Thanks
> > Here is the edited file:
> > [Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3 Sep.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5167043/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3.Sep.2020.xlsx)



Thank you so much @helendallas . Please, consider this unerring file. 
[Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3.Sep.2020_Corrected.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5168650/Final.RBIS.Master.List.of.Taxa_Birds_BDMT.on.3.Sep.2020_Corrected.xlsx)

**Comment by helendallas** [comment]
Thanks team - final Bird Master file:

[RBIS Bird Master List 2020_09_22 Final for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5267593/RBIS.Bird.Master.List.2020_09_22.Final.for.RBIS.V1.xlsx)
