### ISSUE TITLE
Populate Amphibian occurence Data Template

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#6]

**Comment by mmindje** [comment]
The anurans/Amphibians is the next taxon to be worked on.

**Comment by Thacien1** [comment]
> The anurans/Amphibians is the next taxon to be worked on.

Yes @mmindje,  ASAP!

**Comment by DanielIgirimbabazi** [comment]
To kick off this one on Monday!

**Comment by Thacien1** [comment]
> To kick off this one on Monday!

If you are available, we can plan a meeting on Sunday.

**Comment by DanielIgirimbabazi** [comment]
> > To kick off this one on Monday!
> 
> If you are available, we can plan a meeting on Sunday.

Sure! I can be available, let's hear from others

**Comment by mmindje** [comment]
On Sunday, I cannot make it. Maybe we can see on Monday 20th at 10h.

if agree we can meet at https://meet.google.com/ork-cuah-tam with @DanielIgirimbabazi @Thacien1 @Deborahcyu

**Comment by Thacien1** [comment]
> On Sunday, I cannot make it. Maybe we can see on Monday 20th at 10h.
> 
> if agree we can meet at https://meet.google.com/ork-cuah-tam with @DanielIgirimbabazi @Thacien1 @Deborahcyu

Okay my Sir. No problem. See you on Monday.

**Comment by mmindje** [comment]
Hello Team.

Today has been a very productive day compiling the data into the occurrence data sheet,

@Thacien1 you work ib the sheet is to incorporate the coordinates for the VNP wetlands
@Deborahcyu You will assure you work on the UUID for the data
@DanielIgirimbabazi you will work on the date formats

Thacien, for coordinates please look at the attached file

and this link **https://docs.google.com/spreadsheets/d/1418pmXRoHnMG4gvNllxmVGkfpAKQ1DWI/edit#gid=360839583** is the data we should do the above tasks assigned.

On Monday, we shall work on the Taxon validation.
[Coordinate in Decimal degree.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5269740/Coordinate.in.Decimal.degree.xlsx)

**Comment by Thacien1** [comment]
Hello @helendallas  

The updated file of  **Amphibian** **occurrence** **data** is attached.

Kind regards,
**Thacien**

[RBIS.Anurans.Data.file.2020_10_08.Final.for.BDT.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5346265/RBIS.Anurans.Data.file.2020_10_08.Final.for.BDT.xlsx)

**Comment by helendallas** [comment]
@Thacien1 @mmindje Thanks, I am going through it now. 

Question: Are all these sampling methods all distinct?  We want to avoid adding in to many different sampling methods if they are similar.  If they are all distinct then we will need to ask Dimas to add them in before we can upload the Amphibian data.  I have created a ticket asking this to be added to admin functionality

![image](https://user-images.githubusercontent.com/45286876/95583118-f84bd680-0a3b-11eb-974f-b581b48736d1.png)

**Comment by helendallas** [comment]
@Thacien1 @mmindje 
I spent some time going through this data file and checking. At the same time in response to some questions on github (#21), I have created a document to guide you on the checking of the occurrence data file, based on the sort of check I commonly do and which I find useful.

Please go through this and highlight any questions.
[Checking occurrence data file for accuracy 2020_10_09.docx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5355723/Checking.occurrence.data.file.for.accuracy.2020_10_09.docx)


The revised amphibian data file is attached.
[RBIS Amphibian Data 2020_10_09 Draft for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5355722/RBIS.Amphibian.Data.2020_10_09.Draft.for.RBIS.V1.xlsx)

We can also discuss Sampling method on monday

**Comment by mmindje** [comment]
Thank you Hellen

The second and the fourth are similar.
My team shall fix this and add the final file.
Thank you

**Comment by mmindje** [comment]
Attached is the updated File with clear methodologies. 

2 were merged to have 3.

**The three are distinct methodologies**
![image](https://user-images.githubusercontent.com/64961274/95610929-622aa700-0a61-11eb-969b-7e2b9a426e16.png)


[RBIS.Amphibian.Data.2020_10_09.Draft.for.RBIS.V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5356373/RBIS.Amphibian.Data.2020_10_09.Draft.for.RBIS.V1.xlsx)

**Comment by helendallas** [comment]
Thanks, noted
