### ISSUE TITLE
Populate Odonate Master list development

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#7]

**Comment by mmindje** [comment]
Hi All @Thacien1 @DanielIgirimbabazi @Deborahcyu 
I am on this point:
As we had earlier discussed, we said we can go ahead with ANurans but I think let us first start with Odonates and Anuran next. This is because Anurans data are still to be extracted from other sources and decided about all information. 

@helendallas We have decided to work on odonates master list and occurrence data prior to anurans as we still have to sit nad make all new anurans records ready. A full anuran list was got from "https://amphibiansoftheworld.amnh.org/content/search?taxon=&subtree=&subtree_id=&english_name=&author=&year=&country=272" and we thought we need more time to work on the list.

So we opt for Odonates data first as we have these ready

**Comment by helendallas** [comment]
@mmindje Thanks for the update. It seems like the team is progressing well with the odonates

**Comment by coeb1** [comment]
> @mmindje Thanks for the update. It seems like the team is progressing well with the odonates

Yes. So far so good with the master list, then we will keep ahead with the Occurrence records

**Comment by Thacien1** [comment]
Hello Team,

Have a look on Odonates species master-list file. 
[RBIS.Master.List.of.Taxa_Odonates_BDMT _ 26.7. 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4977805/RBIS.Master.List.of.Taxa_Odonates_BDMT._.26.7.2020.xlsx)
 
Thank you

**Comment by helendallas** [comment]
@Thacien1 Thanks, I found the list in an earlier email. I have made a few notes in the attached file. Looking good.
[RBIS.Master.List.of.Taxa_Odonates_BDMT._.26.7.2020_HD.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4993030/RBIS.Master.List.of.Taxa_Odonates_BDMT._.26.7.2020_HD.xlsx)

**Comment by Thacien1** [comment]
> @Thacien1 Thanks, I found the list in an earlier email. I have made a few notes in the attached file. Looking good.
> [RBIS.Master.List.of.Taxa_Odonates_BDMT._.26.7.2020_HD.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/4993030/RBIS.Master.List.of.Taxa_Odonates_BDMT._.26.7.2020_HD.xlsx)

Thank you @helendallas . Let us have a look.

**Comment by Thacien1** [comment]
Final odonates Master list.
[RBIS.Master.List.of.Taxa_Odonates_BDMT_20.8.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5101038/RBIS.Master.List.of.Taxa_Odonates_BDMT_20.8.2020.xlsx)

**Comment by mmindje** [comment]
@helendallas can we leave blank the field for the missed Authors/collector affiliations?

We dug deep from the internet and we could not be sure of the results
1. Saceghem, Van ; 
2.Darling, Gregg & Desire ; 
3. Burmeister et al ; 
4.Hegh, H.

We also asked Erasme whom we thought could be better placed with this information, but unfortunately, he also has none.

**Comment by helendallas** [comment]
@Thacien1 @mmindje Thank you. I will go though this in details after our meeting as there is not much time now.

**Comment by helendallas** [comment]
@Thacien1 @mmindje  I managed to go through the Mater list of Odonata. It is looking great. 
@mmindje The comments above - do they refer to the Odonata Data file? or the master list? I assume the data file.

**Comment by DanielIgirimbabazi** [comment]
> @Thacien1 @mmindje I managed to go through the Mater list of Odonata. It is looking great.
> @mmindje The comments above - do they refer to the Odonata Data file? or the master list? I assume the data file.

Yes Helen, the questions correspond to Odonata Data file.

**Comment by helendallas** [comment]
@DanielIgirimbabazi  My comments 1) refers to the Master file. This ticket is for the master file.  Comments 2) was for the data file, which I have been sent, thank you.  I am still working through the data file. There are several issues. I will share with you once I am done.

**Comment by Thacien1** [comment]
Here below is an **updated Odonata Master file**.

[RBIS.Master.List.of.Taxa_Odonates_BDMT_3.9.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5166932/RBIS.Master.List.of.Taxa_Odonates_BDMT_3.9.2020.xlsx)

**Comment by helendallas** [comment]
@Thacien1 

This looks great thanks.

**Comment by Thacien1** [comment]
Final **Odonata** **MasterList** **file**. 

[RBIS.Master.List.of.Taxa_Odonates_BDMT_11 Sept 2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5208252/RBIS.Master.List.of.Taxa_Odonates_BDMT_11.Sept.2020.xlsx)

**Comment by helendallas** [comment]
@Thacien1 Thanks

Please check:

Odonata | Chlorocyphidae | **Stenocypha** | jacksoni |   | **Chlorocypha** jacksoni | **Chlorocypha** jacksoni Pinhey,   1952

Genus is different in genus column and taxon. Also where did you get the scientific authority as this species is not on GBIF/

Thanks

**Comment by Thacien1** [comment]
> @Thacien1 Thanks
> 
> Please check:
> 
> Odonata | Chlorocyphidae | **Stenocypha** | jacksoni |   | **Chlorocypha** jacksoni | **Chlorocypha** jacksoni Pinhey, 1952
> 
> Genus is different in genus column and taxon. Also where did you get the scientific authority as this species is not on GBIF/
> 
> Thanks

Dear @helendallas . The final Odonats MasterList is attached. The Authorship of this *Stenocypha* *jacksoni* was found on this link **http://addo.adu.org.za/index.php?taxon_id=12300**

Thank you.

[RBIS.Master.List.of.Taxa_Odonates_BDMT_14.Sept.2020.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5217776/RBIS.Master.List.of.Taxa_Odonates_BDMT_14.Sept.2020.xlsx)

**Comment by helendallas** [comment]
Thanks team - final Odonata master file:

[RBIS Odonata Master List 2020_09_22 Final for RBIS V1.xlsx](https://github.com/mmindje/Data-management-FRC-RBIS/files/5267581/RBIS.Odonata.Master.List.2020_09_22.Final.for.RBIS.V1.xlsx)
