### ISSUE TITLE
Populate Macro-invertebrate Data Template

### ISSUE THREAD

**Issue by mmindje** [mmindje/Data-management-FRC-RBIS#8]

**Comment by mmindje** [comment]
@helendallas , we have been developing the master list  for macroinvertebrate.

As we do not have spp ID to species level, what do you advise us to fill in the scientific name and authorship, origin, endemism, and the IUCN status ?

We got challenged. This taxa is still poorly studied to spp level.

**Comment by helendallas** [comment]
@mmindje Where data are only to family it is not possible to fill in the scientific name and authorship, origin, endemism, and the IUCN status - unless the whole family is endemic for example. So these can be left blank.

**Comment by Thacien1** [comment]
> @mmindje Where data are only to family it is not possible to fill in the scientific name and authorship, origin, endemism, and the IUCN status - unless the whole family is endemic for example. So these can be left blank.

Thank you @helendallas  for the clarification.
